### PR TITLE
Merge EyoWeiChin-Parser-Update

### LINKED ISSUE #235: [PE-D] Search term does not work with trailing spaces
Search by name does not work if there are extra spaces at the end of the <search term> and this constraints seems to be missing the UG. 
You can consider to either allow this to work by trimming the <search term> or adding the constraint in the UG.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: kaijiel24/ped#7

### LINKED ISSUE #250: [PE-D] bug in search command
Your search command is working fine, able to search for number, words and special characters.
But it fails to search if i added an empty space behind, please refer to the attachment for reference. Perhaps, you might want to think of using trim() function in your search?

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: LIU-YiFeng-1/ped#4

### LINKED ISSUE #251: [PE-D] another bug in seach command
I decided to open another issue for search command. This bus is also pertaining to adding extra spaces infront of the search keyword.

It works when I added 1 extra space but soon failed when I added 2 extra spaces. I am not sure what is the cause of that, perhaps you might you to investigate.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: LIU-YiFeng-1/ped#5

### PR DESCRIPTION
**Pull request by EyoWeiChin**
Update:
- BrowseParser and SearchParser to be more consistent
- SearchParser to fix trailing and prepend whitespace bug
- BrowseCommand and SearchCommand to accommodate the changes
- input.txt and EXPECTED.txt to further test the update

Fixes #251, #250, #235

### CODE REVIEW

**Review by OngDeZhi — APPROVED** [review]
Looks good! Thanks for helping to make it consistent :).

File: src/main/java/anichan/commands/BrowseCommand.java [hunk 1]
```diff
@@ -103,17 +107,17 @@ private String buildBrowseOutput(ArrayList<Anime> usableList) throws AniExceptio
             String animeName = browseAnime.getAnimeName();
             //Removes non-ascii and trim long titles.
             animeName = animeName.replaceAll(ASCII_ONLY_REGEX, EMPTY_STRING);
-            if (animeName.length() >= 51) {
-                animeName = animeName.substring(0, 48);
-                animeName += INDICATE_MORE;
+            if (animeName.length() >= MAX_NAME_LEN) {
```
Comment (ChanJianHao) [inline src/main/java/anichan/commands/BrowseCommand.java:110]: Great work refactoring numbers!

**Review by ChanJianHao — APPROVED** [review]
LGTM 👍🏻
